{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apm-server.fullname" . }}
  labels:
    app: {{ template "apm-server.name" . }}
    chart: {{ template "apm-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8200
  selector:
    app: {{ template "apm-server.name" . }}
    release: {{ .Release.Name }}
{{- end }}